"use client";

import { useState } from "react";
import StepShell from "./StepShell";
import ContinueButton from "./ContinueButton";

export default function AccountStep({
  stepNumber,
  totalSteps,
  onSubmit,
  onLogin,
  loading,
  error,
}: {
  stepNumber: number;
  totalSteps: number;
  onSubmit: (name: string, email: string, password: string) => void;
  onLogin: (email: string, password: string) => void;
  loading: boolean;
  error: string | null;
}) {
  const [mode, setMode] = useState<"signup" | "login">("signup");
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const signupValid = name.trim().length > 0 && /\S+@\S+\.\S+/.test(email) && password.length >= 6;
  const loginValid = /\S+@\S+\.\S+/.test(email) && password.length >= 6;
  const valid = mode === "signup" ? signupValid : loginValid;

  return (
    <StepShell
      stepKey="account"
      stepNumber={stepNumber}
      totalSteps={totalSteps}
      title={mode === "signup" ? "Create your free FitMind account" : "Welcome back"}
      footer={
        <ContinueButton
          onClick={() =>
            mode === "signup"
              ? onSubmit(name, email, password)
              : onLogin(email, password)
          }
          disabled={!valid}
          loading={loading}
          label={mode === "signup" ? "Create account" : "Log in"}
        />
      }
    >
      <p className="text-sm text-muted">
        {mode === "signup"
          ? "Your real plan is generated by the same AI that powers the FitMind app — we just need an account to save it to."
          : "Log in with your existing account to continue."}
      </p>

      <div className="mt-6 flex flex-col gap-4">
        {mode === "signup" && (
          <input
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Full name"
            className="rounded-xl border border-border bg-surface px-4 py-3.5 outline-none focus:border-brand/60"
          />
        )}
        <input
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          type="email"
          placeholder="Email address"
          className="rounded-xl border border-border bg-surface px-4 py-3.5 outline-none focus:border-brand/60"
        />
        <input
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          type="password"
          placeholder="Password (min 6 characters)"
          className="rounded-xl border border-border bg-surface px-4 py-3.5 outline-none focus:border-brand/60"
        />
      </div>

      {error && <p className="mt-4 text-sm text-red-400">{error}</p>}

      <p className="mt-6 text-center text-sm text-muted">
        {mode === "signup" ? (
          <>
            Already have an account?{" "}
            <button
              onClick={() => { setMode("login"); }}
              className="font-semibold text-brand hover:underline"
            >
              Log in
            </button>
          </>
        ) : (
          <>
            Don&apos;t have an account?{" "}
            <button
              onClick={() => { setMode("signup"); }}
              className="font-semibold text-brand hover:underline"
            >
              Sign up
            </button>
          </>
        )}
      </p>
    </StepShell>
  );
}
